@startuml
skinparam monochrome reverse
skinparam ArchimateBackgroundColor #ffffff
skinparam	shadowing false
skinparam Note {
	BackgroundColor black
	FontColor #ffffff
}

left header
<font color=000 size=18><b>Package:</b> Worker

<font color=000 size=16><b>ID:</b> taskState
<font color=000 size=16><b>Назва:</b> Отримання інформації щодо завдання.
<font color=000 size=16><b>Учасники:</b> Робітник проекта, Система.
<font color=000 size=16><b>Передумови:</b> Робітник бажає отримати інформацію про своє завдання.
<font color=000 size=16><b>Результат:</b> Інформацію отримано.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Завдання відсутнє 

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Робітник|
start
: Натискає кнопку "Отримати завдання";

|Система|

: Оброблює запит;
note right

	EX_00

end note

: Повертає інформацію щодо завдання;

|Робітник|

: Отримає відповідну сторінку с завданням;

stop;

right footer


Project Manager
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
