-- MySQL Script generated by MySQL Workbench
-- Wed May 13 18:11:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idroles` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idroles`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `idprojects` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `startdate` VARCHAR(45) NOT NULL,
  `deadline` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprojects`));


-- -----------------------------------------------------
-- Table `mydb`.`users_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_projects` (
  `users_idusers` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  `roles_idroles1` INT NOT NULL,
  `projects_idprojects` INT NOT NULL,
  PRIMARY KEY (`users_idusers`),
  INDEX `fk_users_projects_users_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_users_projects_roles1_idx` (`roles_idroles1` ASC) VISIBLE,
  INDEX `fk_users_projects_projects1_idx` (`projects_idprojects` ASC) VISIBLE,
  CONSTRAINT `fk_users_projects_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_projects_roles1`
    FOREIGN KEY (`roles_idroles1`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_projects_projects1`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `mydb`.`projects` (`idprojects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`users_data_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_data_projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_data_projects` (
  `iddata` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  `projects_idprojects` INT NOT NULL,
  PRIMARY KEY (`iddata`),
  INDEX `fk_users_data_projects_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_users_data_projects_projects1_idx` (`projects_idprojects` ASC) VISIBLE,
  CONSTRAINT `fk_users_data_projects_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_data_projects_projects1`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `mydb`.`projects` (`idprojects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`data_dataspec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`data_dataspec` ;

CREATE TABLE IF NOT EXISTS `mydb`.`data_dataspec` (
  `iddata_dataspec` INT NOT NULL,
  `datasetName` VARCHAR(100) NULL,
  `datasetDescription` VARCHAR(45) NULL,
  `datasetTimeAdded` DATETIME NULL,
  `comment` VARCHAR(500) NULL,
  `users_data_projects_iddata` INT NOT NULL,
  PRIMARY KEY (`iddata_dataspec`),
  INDEX `fk_data_dataspec_users_data_projects1_idx` (`users_data_projects_iddata` ASC) VISIBLE,
  CONSTRAINT `fk_data_dataspec_users_data_projects1`
    FOREIGN KEY (`users_data_projects_iddata`)
    REFERENCES `mydb`.`users_data_projects` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
